### ISSUE TITLE
New Robot Remote Server in Clojure 

### ISSUE THREAD

**Issue by cneira** [robotframework/RemoteInterface#3]
Hi @pekkaklarck ,

I have updated the old remote server written in clojure as it was not working at that time, and added a couple of keywords to execute jobs on the mainframe this is the repo with the current work
https://github.com/cneira/RoboZ

Could you add my server to the current remote server list ?

Bests

**Comment by pekkaklarck** [comment]
FSorry, hadn't noticed this issue earlier. I'm a bit confused about RoboZ. Is it a generic remote server for Clojure or a server dedicated for mainframe testing? If it's both, that's a bit weird and I'd prefer splitting the generic Clojure part into a separate server that the mainframe server could then use.
